---
title: "SDM_Abgabe_1"
author: "Gabriel Valentin Behnke"
date: "20.04.2021"
output: html_document
---
<style>
body {
  color: white;
  background-color: darkgreen;
 
}
p {
  color: white;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Hello R, Hello GitHub

## Tasks

1. Assign the value of 2 to a variable called a and the value of 5 to a variable called b.
2. Compute the sum, difference, product and ratio of a and b (a always in the first place) and store the results to four different variables called r1, r2, r3, and r4.
3. Create a vector v1 which contains the values stored within the four variables from step 2.
4. Add a fifth entry to vector v1 which represents a by the power of b (i.e. a**b).
5. Show the content of vector v1 (e.g. use the print function or just type the variable name in a separate row).
6. Create a second vector v2 which contains information on the type of mathematical operation used to derive the five results. Hence this vector should have five entries of values sum, difference,…
7. Show the content of vector v2.
8. Combine the two vectors v1 and v2 into a data frame called df. Each vector should become one column of the data frame so you will end up with a data frame having 5 rows and 2 columns.
9. Make sure that the column with the data of v1 is named Results and v2 is named Operation.
10. Show the entire content of df.
11. Show just the entry of the 3 row and 1 column.

## Solution
```
a<-2
b<-5
r1<-a+b
r2<-a-b
r3<-a*b
r4<-a/b
v1<-c(r1,r2,r3,r4)
r5<-a**b
v1<-c(r1,r2,r3,r4,r5)
v1
v2<-c("sum","difference","product","ratio","power")
print(v2)
Results<-v1
Operation<-v2
df<-data.frame(Results,Operation)
df
df$Result[df$Operation=="product"]
```

## Plot test

<table>
  <tr>
    <th>Results</th>
    <th>Operation</th>
  </tr>
  <tr>
    <td>7</td>
    <td>Sum</td>
   </tr>
   <tr>
     <td>-3</td>
     <td>Difference</td>
     </tr>
       <tr>
    <td>10</td>
    <td>Product</td>
   </tr>
   <tr>
     <td>.4</td>
     <td>Ratio</td>
       <tr>
    <td>32</td>
<td>Power</td>
</tr>
</table>
